{% set name = "dotnetcore-sdk" %}
{% set version = "3.1.100" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://dot.net/v1/dotnet-install.sh  # [not win]
    sha256: 7cf038c274862c160c2fe8cfc0ea7471b48d1ac05cb201b7717d53354ccd139c  # [not win]
  - url: https://dot.net/v1/dotnet-install.ps1  # [win]
    sha256: 71a888f99a73936de8cbcc494df2706f77a69a98a9962a0351052c350f95be39  # [win]

build:
  number: 0
  detect_binary_files_with_prefix: False
  missing_dso_whitelist:
  # .NET assemblies are technically PE files with a small stub that links to
  # mscoree.dll. That link exists as a compatibility shim for older versions of
  # Windows, and should be ignored when determining the actual linking requirements
  # for the .NET Core SDK.
  - "*/mscoree.dll"
  # The other source of overlinking errors is that even on non-Windows systems, the
  # .NET Core SDK provides some packages that target Windows native dependencies to
  # allow for cross-compiling and multi-targeting.
  # Here, we whitelist the few native dependencies brought in by these packages.
  - "*/WINTRUST.dll" # used by comhost.dll, a native component in Microsoft.NETCore.App.Host.win-x64.
  - "*/VERSION.dll" # used by dbgshim.dll, a native component used to provide native debugging shims.
  - "*/SHLWAPI.dll" # part of the core Windows system libraries, used by coreclr.dll


requirements:
  build:
  - {{ compiler('c') }}
  run_constrained:
  - __osx >=10.13  # [osx]
  run:
    - libcurl  # [linux]
    - openssl  # [linux]
    - icu  # [linux]

test:
  commands:
  - dotnet --version

about:
  home: https://github.com/dotnet/core-sdk
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: '.NET Core is a cross-platform version of .NET for building websites, services, and console apps.'

  description: |
    .NET Core is a free and open-source, managed computer software framework for Windows, Linux, and macOS operating systems.
  doc_url: http://docs.microsoft.com/dotnet
  dev_url: https://github.com/dotnet/core-sdk

extra:
  recipe-maintainers:
    - cgranade
